import Head from 'next/head'
import Image from 'next/image'

import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';


import Container from '@mui/material/Container';

import InputLabel from '@mui/material/InputLabel';
import Grid from '@mui/material/Grid';
import FormControl from '@mui/material/FormControl';
import FormLabel from '@mui/material/FormLabel';
import FormControlLabel from '@mui/material/FormControlLabel';

import Radio from '@mui/material/Radio';
import RadioGroup from '@mui/material/RadioGroup';


import TextField from '@mui/material/TextField';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

import FolderView from '../components/FolderView';
import Description from '../components/Description';

export default function Home() {

  return (
    <div>
      <Head>
        <title>Lifting State Up.</title>
        <meta name="description" content="Generated by a copy/paste of an existing create next app project and then manually gutted and replaced with new content" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            Lifting State
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="md">
          <Typography variant='p' component='p'>
            This starter kit is currently loading the same data file directly in the <code>&lt;Description /&gt;</code> and <code>&lt;FolderView /&gt;</code> components. Our task will be to load the data once and have it shared between the two components.
          </Typography>
          <hr />
          <Description />
          <hr />
          <FolderView />
        </Container>
      </main>
    </div>
  )
}
