import Head from 'next/head'
import Image from 'next/image'

import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';


import Container from '@mui/material/Container';

import InputLabel from '@mui/material/InputLabel';
import Grid from '@mui/material/Grid';
import FormControl from '@mui/material/FormControl';
import FormLabel from '@mui/material/FormLabel';
import FormControlLabel from '@mui/material/FormControlLabel';

import Radio from '@mui/material/Radio';
import RadioGroup from '@mui/material/RadioGroup';


import TextField from '@mui/material/TextField';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

import FolderView from '../components/FolderView';
import Description from '../components/Description';
import projectFiles from '../projectFiles.json';
import { useState } from 'react';

export default function Home() {
  const [description, setDescription] = useState(projectFiles.description);
  const [activeNode, setActiveNode] = useState('');
  const [nodes, setNodes] = useState(projectFiles);

  const handleClick = (evt) => {
    const clickedNode = evt.target.innerText.trim();
    setActiveNode(clickedNode);
    console.log('Clicked node name:', clickedNode);
    console.log('My tree nodes', nodes);
    const found = findDescription(nodes, clickedNode);
    setDescription(found); // and now, my <Description /> child will have that clicked node's description.
  }

  /**
   * findDescription is going to search a tree-like structure of
   * project file and folder names to find a given node's description.
   * @param {object} aNode Object representing project files/folders
   * @param {string} aNode.nodeName Name of the file or folder
   * @param {string} aNode.description Description of the file or folder
   * @param {object[]} aNode.childNodes Child nodes (an empty array or an array of nodes)
   * @param {string} searchName The name to search for with the node or its children
   */
  const findDescription = (aNode, searchName) => {
    let found = '';
    if(aNode.nodeName === searchName) {
      found = aNode.description;
    } else {
      // check all the child nodes
      for(let index = 0; index < aNode.childNodes.length; index++) {
        let child = aNode.childNodes[index];
        found = findDescription(child, searchName);
        if(found) {
          // early exit of loop
          index = aNode.childNodes.length;
        }
      }
    }
    return found;
  }

  return (
    <div>
      <Head>
        <title>Lifting State Up.</title>
        <meta name="description" content="Generated by a copy/paste of an existing create next app project and then manually gutted and replaced with new content" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            Lifting State
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="md">
          <Typography variant='p' component='p'>
            This starter kit is currently loading the same data file directly in the <code>&lt;Description /&gt;</code> and <code>&lt;FolderView /&gt;</code> components. Our task will be to load the data once and have it shared between the two components.
          </Typography>
          <hr />
          <Description description={description} />
          <hr />
          <FolderView 
            handleClick={handleClick}
            activeNode={activeNode}
            nodes={nodes}
            />
        </Container>
      </main>
    </div>
  )
}
